def get_sample_bids() -> list[dict[str, object]]:
    return [
        {
            "bid_id": "R26BK00000001-000",
            "status": "검토중",
            "status_variant": "primary",
            "business_type": "용역",
            "domain_type": "내자",
            "notice_type": "등록공고",
            "stage_label": "입찰공고",
            "step_label": "공고등록",
            "progress_label": "진행완료",
            "bid_no": "R26BK00000001-000",
            "bid_seq": "000",
            "title": "2026년 중소기업 인력지원사업 종합관리시스템 유지보수 용역",
            "notice_org": "조달청 경남지방조달청",
            "demand_org": "중소벤처기업진흥공단",
            "budget_amount": "120,000,000",
            "presmpt_prce": "109,090,909",
            "vat": "10,909,091",
            "notice_kind": "실공고(등록공고)",
            "posted_at": "2026-03-12 21:13:29",
            "closed_at": "2026-03-18 14:00",
            "opened_at": "2026-03-18 15:00",
            "ref_no": "용인시 공고 제2026-885호",
            "bid_method": "전자입찰",
            "award_method": "소액수의견적",
            "award_method_detail": "소액수의견적(2인 이상 견적 제출)",
            "sucsfbid_lwlt_rate": "88.000 %",
            "contract_method": "수의계약",
            "contract_scope": "총액계약",
            "intl_division": "국내입찰",
            "creditor_name": "용인시장",
            "consortium_submit": "(없음)공동수급불허",
            "domestic_international_reason": "국제입찰 비대상(고시금액 이하 또는 대상기관 아님)",
            "rebid_allowed": "허용",
            "auto_bid_program": "사용",
            "site_briefing_place": "없음",
            "site_briefing_at": "없음",
            "detail_rows": [
                {
                    "left_label": "공고종류",
                    "left_value": "실공고(등록공고)",
                    "right_label": "게시일시",
                    "right_value": "2026-03-12 21:13:29",
                },
                {
                    "left_label": "입찰공고번호",
                    "left_value": "R26BK00000001-000",
                    "right_label": "참조번호",
                    "right_value": "용인시 공고 제2026-885호",
                },
                {
                    "left_label": "공고명",
                    "left_value": "2026년 사회적 고립청년 지원사업 운영 용역",
                    "right_label": "업무구분",
                    "right_value": "일반용역",
                },
                {
                    "left_label": "입찰방식",
                    "left_value": "전자입찰",
                    "right_label": "낙찰방법",
                    "right_value": "소액수의견적",
                },
                {
                    "left_label": "낙찰방법세부기준",
                    "left_value": "소액수의견적(2인 이상 견적 제출)",
                    "right_label": "낙찰하한율",
                    "right_value": "88.000 %",
                },
                {
                    "left_label": "계약방법",
                    "left_value": "수의계약",
                    "right_label": "계약구분",
                    "right_value": "총액계약",
                },
                {
                    "left_label": "국제입찰구분",
                    "left_value": "국내입찰",
                    "right_label": "채권자명",
                    "right_value": "용인시장",
                },
                {
                    "left_label": "공동수급협정서 제출 및 구성방식",
                    "left_value": "(없음)공동수급불허",
                    "right_label": "국내/국제입찰사유",
                    "right_value": "국제입찰 비대상(고시금액 이하 또는 대상기관 아님)",
                },
                {
                    "left_label": "재입찰여부",
                    "left_value": "허용",
                    "right_label": "자동추첨프로그램",
                    "right_value": "사용",
                },
                {
                    "left_label": "현장설명회장소",
                    "left_value": "없음",
                    "right_label": "현장설명일시",
                    "right_value": "없음",
                },
                {
                    "left_label": "공고기관",
                    "left_value": "조달청 경남지방조달청",
                    "right_label": "수요기관",
                    "right_value": "중소벤처기업진흥공단",
                },
                {
                    "left_label": "추정가격",
                    "left_value": "109,090,909",
                    "right_label": "부가가치세",
                    "right_value": "10,909,091",
                },
                {
                    "left_label": "입찰마감일시",
                    "left_value": "2026-03-18 14:00",
                    "right_label": "개찰일시",
                    "right_value": "2026-03-18 15:00",
                },
            ],
            "favorite": True,
            "qualification": {
                "industry_limited": True,
                "international_bid": "국내입찰",
                "rebid_allowed": "허용",
                "bid_participation_limit": "없음",
                "license_limits": [
                    "소프트웨어사업자(컴퓨터관련서비스사업)",
                    "정보통신공사업",
                ],
                "permitted_industries": ["데이터서비스", "시스템유지보수서비스"],
                "regions": ["전국"],
                "reference_infos": [
                    {
                        "name": "정보통신공사업",
                        "code": "INFO-001",
                        "law_name": "정보통신공사업법",
                        "source_api_name": "industryBaseLaw",
                    },
                    {
                        "name": "소프트웨어사업자(컴퓨터관련서비스사업)",
                        "code": "SW-002",
                        "law_name": "소프트웨어진흥법",
                        "source_api_name": "industryBaseLaw",
                    },
                ],
                "consortium_method": "공동수급불허",
                "qualification_summary": "소프트웨어사업자 등록 및 유사 유지보수 수행 실적 필요",
            },
            "business_info": {
                "service_division": "일반용역",
                "public_procurement_cls": "데이터서비스",
                "tech_eval_rate": "80",
                "price_eval_rate": "20",
                "info_biz": "Y",
            },
            "attachments": [
                {
                    "name": "입찰공고문.hwpx",
                    "type": "일반",
                    "source": "공고첨부",
                    "url": "#",
                },
                {
                    "name": "과업지시서.pdf",
                    "type": "일반",
                    "source": "공고첨부",
                    "url": "#",
                },
                {
                    "name": "제안요청서.hwpx",
                    "type": "e발주",
                    "source": "e발주",
                    "url": "#",
                },
            ],
            "description_text": "사회적 고립청년 발굴 및 지원체계 운영을 위한 종합관리시스템 유지보수 사업이다.",
            "timeline": [
                {
                    "stage": "사전규격",
                    "status": "완료",
                    "number": "R26BD00019757",
                    "date": "2026-03-10 09:00",
                    "meta": "의견등록마감 2026-03-12",
                },
                {
                    "stage": "입찰공고",
                    "status": "진행중",
                    "number": "R26BK00000001-000",
                    "date": "2026-03-12 09:00",
                    "meta": "입찰마감 2026-03-18 14:00",
                },
                {
                    "stage": "개찰/낙찰",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "개찰예정 2026-03-18 15:00",
                },
                {
                    "stage": "계약",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "낙찰 후 생성",
                },
            ],
            "history": [
                {
                    "changed_at": "2026-03-12 10:12",
                    "item": "공고명",
                    "before": "중소기업 인력지원사업 유지보수",
                    "after": "2026년 중소기업 인력지원사업 종합관리시스템 유지보수 용역",
                },
                {
                    "changed_at": "2026-03-13 09:05",
                    "item": "입찰마감일시",
                    "before": "2026-03-17 18:00",
                    "after": "2026-03-18 14:00",
                },
            ],
        },
        {
            "bid_id": "R26BK00000002-000",
            "status": "수집완료",
            "status_variant": "secondary",
            "business_type": "물품",
            "domain_type": "내자",
            "notice_type": "등록공고",
            "stage_label": "입찰공고",
            "step_label": "공고등록",
            "progress_label": "진행완료",
            "bid_no": "R26BK00000002-000",
            "bid_seq": "000",
            "title": "전남소방본부 구급소모품 구매",
            "notice_org": "전라남도",
            "demand_org": "전라남도 소방본부",
            "budget_amount": "85,500,000",
            "presmpt_prce": "77,727,273",
            "vat": "7,772,727",
            "notice_kind": "등록공고",
            "posted_at": "2026-03-13 10:00:00",
            "closed_at": "2026-03-20 10:00",
            "opened_at": "2026-03-20 11:00",
            "ref_no": "전남소방본부 물품-2026-44",
            "bid_method": "전자입찰",
            "award_method": "적격심사",
            "award_method_detail": "중소기업자간 경쟁물품 계약이행능력심사",
            "sucsfbid_lwlt_rate": "87.995 %",
            "contract_method": "제한경쟁",
            "contract_scope": "총액계약",
            "intl_division": "국내입찰",
            "creditor_name": "전라남도 소방본부장",
            "consortium_submit": "공동수급가능",
            "domestic_international_reason": "국내 일반 공고",
            "rebid_allowed": "허용",
            "auto_bid_program": "사용",
            "site_briefing_place": "없음",
            "site_briefing_at": "없음",
            "detail_rows": [
                {
                    "left_label": "공고종류",
                    "left_value": "등록공고",
                    "right_label": "게시일시",
                    "right_value": "2026-03-13 10:00:00",
                },
                {
                    "left_label": "입찰공고번호",
                    "left_value": "R26BK00000002-000",
                    "right_label": "참조번호",
                    "right_value": "전남소방본부 물품-2026-44",
                },
                {
                    "left_label": "공고명",
                    "left_value": "전남소방본부 구급소모품 구매",
                    "right_label": "업무구분",
                    "right_value": "물품",
                },
                {
                    "left_label": "입찰방식",
                    "left_value": "전자입찰",
                    "right_label": "낙찰방법",
                    "right_value": "적격심사",
                },
                {
                    "left_label": "낙찰방법세부기준",
                    "left_value": "중소기업자간 경쟁물품 계약이행능력심사",
                    "right_label": "낙찰하한율",
                    "right_value": "87.995 %",
                },
                {
                    "left_label": "계약방법",
                    "left_value": "제한경쟁",
                    "right_label": "계약구분",
                    "right_value": "총액계약",
                },
                {
                    "left_label": "공고기관",
                    "left_value": "전라남도",
                    "right_label": "수요기관",
                    "right_value": "전라남도 소방본부",
                },
                {
                    "left_label": "추정가격",
                    "left_value": "77,727,273",
                    "right_label": "부가가치세",
                    "right_value": "7,772,727",
                },
            ],
            "favorite": False,
            "qualification": {
                "industry_limited": False,
                "international_bid": "국내입찰",
                "rebid_allowed": "허용",
                "bid_participation_limit": "없음",
                "license_limits": [],
                "permitted_industries": [],
                "regions": ["전국"],
                "reference_infos": [],
                "consortium_method": "공동수급가능",
                "qualification_summary": "기본 참가자격 충족 시 참여 가능",
            },
            "business_info": {
                "product_class_limited": "Y",
                "manufacturing_required": "N",
                "detail_product_no": "4214252301",
                "detail_product_name": "구급용소모품세트",
                "product_qty": "1식",
                "delivery_condition": "수요기관희망장소입고도",
            },
            "attachments": [
                {
                    "name": "규격서.zip",
                    "type": "일반",
                    "source": "공고첨부",
                    "url": "#",
                },
            ],
            "description_text": "전남소방본부 구급 현장에서 사용하는 소모품을 연간 단가계약 형태로 구매하는 물품 공고다.",
            "timeline": [
                {
                    "stage": "사전규격",
                    "status": "완료",
                    "number": "R26BD00020002",
                    "date": "2026-03-11 15:00",
                    "meta": "사전 검토 완료",
                },
                {
                    "stage": "입찰공고",
                    "status": "진행중",
                    "number": "R26BK00000002-000",
                    "date": "2026-03-13 10:00",
                    "meta": "입찰마감 2026-03-20 10:00",
                },
                {
                    "stage": "개찰/낙찰",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "예정",
                },
                {
                    "stage": "계약",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "예정",
                },
            ],
            "history": [],
        },
        {
            "bid_id": "R26BK00000003-000",
            "status": "관심",
            "status_variant": "warning",
            "business_type": "공사",
            "domain_type": "내자",
            "notice_type": "재공고",
            "stage_label": "입찰공고",
            "step_label": "공고등록",
            "progress_label": "진행완료",
            "bid_no": "R26BK00000003-000",
            "bid_seq": "000",
            "title": "지방도 840호선 국영읍 신기 노후포장 보수공사",
            "notice_org": "전라남도",
            "demand_org": "전라남도",
            "budget_amount": "1,580,000,000",
            "presmpt_prce": "1,436,363,636",
            "vat": "143,636,364",
            "notice_kind": "실공고(등록공고)",
            "posted_at": "2026-03-10 09:00:00",
            "closed_at": "2026-03-17 18:00",
            "opened_at": "2026-03-18 11:00",
            "ref_no": "전라남도 공고 제2026-302호",
            "bid_method": "전자입찰",
            "award_method": "적격심사",
            "award_method_detail": "지방자치단체 입찰시 낙찰자 결정기준 적용",
            "sucsfbid_lwlt_rate": "87.745 %",
            "contract_method": "제한경쟁",
            "contract_scope": "총액계약",
            "intl_division": "국내입찰",
            "creditor_name": "전라남도지사",
            "consortium_submit": "(전자)공동이행 가능",
            "domestic_international_reason": "국내 시설 공고",
            "rebid_allowed": "허용",
            "auto_bid_program": "사용",
            "site_briefing_place": "현장설명 없음",
            "site_briefing_at": "없음",
            "detail_rows": [
                {
                    "left_label": "공고종류",
                    "left_value": "실공고(등록공고)",
                    "right_label": "게시일시",
                    "right_value": "2026-03-10 09:00:00",
                },
                {
                    "left_label": "입찰공고번호",
                    "left_value": "R26BK00000003-000",
                    "right_label": "참조번호",
                    "right_value": "전라남도 공고 제2026-302호",
                },
                {
                    "left_label": "공고명",
                    "left_value": "지방도 840호선 국영읍 신기 노후포장 보수공사",
                    "right_label": "업무구분",
                    "right_value": "공사",
                },
                {
                    "left_label": "입찰방식",
                    "left_value": "전자입찰",
                    "right_label": "낙찰방법",
                    "right_value": "적격심사",
                },
                {
                    "left_label": "낙찰방법세부기준",
                    "left_value": "지방자치단체 입찰시 낙찰자 결정기준 적용",
                    "right_label": "낙찰하한율",
                    "right_value": "87.745 %",
                },
                {
                    "left_label": "계약방법",
                    "left_value": "제한경쟁",
                    "right_label": "계약구분",
                    "right_value": "총액계약",
                },
                {
                    "left_label": "공동수급협정서 제출 및 구성방식",
                    "left_value": "(전자)공동이행 가능",
                    "right_label": "국내/국제입찰사유",
                    "right_value": "국내 시설 공고",
                },
                {
                    "left_label": "재입찰여부",
                    "left_value": "허용",
                    "right_label": "자동추첨프로그램",
                    "right_value": "사용",
                },
                {
                    "left_label": "공고기관",
                    "left_value": "전라남도",
                    "right_label": "수요기관",
                    "right_value": "전라남도",
                },
                {
                    "left_label": "추정가격",
                    "left_value": "1,436,363,636",
                    "right_label": "부가가치세",
                    "right_value": "143,636,364",
                },
                {
                    "left_label": "입찰마감일시",
                    "left_value": "2026-03-17 18:00",
                    "right_label": "개찰일시",
                    "right_value": "2026-03-18 11:00",
                },
                {
                    "left_label": "현장설명회장소",
                    "left_value": "현장설명 없음",
                    "right_label": "현장설명일시",
                    "right_value": "없음",
                },
            ],
            "favorite": True,
            "qualification": {
                "industry_limited": True,
                "international_bid": "국내입찰",
                "rebid_allowed": "허용",
                "bid_participation_limit": "지역 제한",
                "license_limits": ["포장공사업", "토목공사업"],
                "permitted_industries": ["도로유지보수공사"],
                "regions": ["전라남도"],
                "reference_infos": [
                    {
                        "name": "포장공사업",
                        "code": "CONS-101",
                        "law_name": "건설산업기본법",
                        "source_api_name": "industryBaseLaw",
                    },
                    {
                        "name": "토목공사업",
                        "code": "CONS-102",
                        "law_name": "지방계약법 시행규칙",
                        "source_api_name": "industryBaseLaw",
                    },
                ],
                "consortium_method": "공동수급가능",
                "qualification_summary": "지역 제한 및 면허 조건 충족 필요",
            },
            "business_info": {
                "main_construction_type": "포장공사업",
                "construction_site_region": "전라남도 국영읍",
                "industry_eval_rate": "69.79",
                "joint_contract_required": "N",
                "construction_law_applied": "Y",
                "market_entry_allowed": "N",
            },
            "attachments": [
                {
                    "name": "공고문.pdf",
                    "type": "일반",
                    "source": "공고첨부",
                    "url": "#",
                },
                {
                    "name": "공내역서.xlsx",
                    "type": "일반",
                    "source": "공고첨부",
                    "url": "#",
                },
            ],
            "description_text": "지방도 840호선 구간의 노후 포장을 보수해 안전성과 주행 품질을 개선하는 공사다.",
            "timeline": [
                {
                    "stage": "발주계획",
                    "status": "완료",
                    "number": "R26DD00030001",
                    "date": "2026-02-25 09:00",
                    "meta": "도로 보수 사업",
                },
                {
                    "stage": "사전규격",
                    "status": "완료",
                    "number": "R26BD00030021",
                    "date": "2026-03-01 11:00",
                    "meta": "의견등록 종료",
                },
                {
                    "stage": "입찰공고",
                    "status": "진행중",
                    "number": "R26BK00000003-000",
                    "date": "2026-03-10 09:00",
                    "meta": "입찰마감 2026-03-17 18:00",
                },
                {
                    "stage": "개찰/낙찰",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "개찰예정 2026-03-18 11:00",
                },
                {
                    "stage": "계약",
                    "status": "미도달",
                    "number": "없음",
                    "date": "없음",
                    "meta": "낙찰 후 생성",
                },
            ],
            "history": [
                {
                    "changed_at": "2026-03-11 14:10",
                    "item": "참가가능지역",
                    "before": "전국",
                    "after": "전라남도",
                },
            ],
        },
    ]
